CivilizationReplica/Models/Nation.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CivilizationReplica.Models
{
    [Table("Nations")]
    public class Nation
    {
        [Key]
        public int Id { get; set; }
        public string NationName { get; set; }
        public string GovernmentType { get; set; }
        public string EconomyType { get; set; }
        public string GeographyType { get; set; }

        public int Capital { get; set; }
        public int Resources { get; set; }
        public int Population { get; set; }
        public int Stability { get; set; }

        public virtual User User { get; set; }

        public Nation()
        {}
        public Nation(string Nation, string Government, string Economy, string Geography)
        {
            NationName = Nation;
            GovernmentType = Government;
            EconomyType = Economy;
            GeographyType = Geography;
            Capital = 1000;
            Resources = 50;
            Population = 10000;
            Stability = 50;
        }
    }
}

CivilizationReplica/Controllers/NationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CivilizationReplica.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CivilizationReplica.Controllers
{
    public class NationController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<User> _userManager;

        public NationController(UserManager<User> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public IActionResult Index(string id)
        {
            ViewBag.user = _db.Users.FirstOrDefault(x => x.Id == id);
            return View();
        }


        public IActionResult Create(string id)
        {
            ViewBag.user = _db.Users.FirstOrDefault(x => x.Id == id);
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreateNation(Nation nation)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            nation.User = currentUser;
            _db.Nations.Add(nation);
            _db.SaveChanges();
            return RedirectToAction("Index", new { id = userId });
        }

        public async Task<IActionResult> Game()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var thisNation = _db.Nations.Include(m => m.User)
                                .FirstOrDefault(m => m.User.Id == userId);
            return View(thisNation);
        }
        public IActionResult EventGenerator()
        {
            var randomEvent = _db.Events.OrderBy(r => Guid.NewGuid());
            return Json(randomEvent);
        }
    }
}

CivilizationReplica/Views/Nation/Create.cshtml
@model CivilizationReplica.Models.Nation

<h3>Build your Nation</h3>

<div>
    @using (Html.BeginForm("Create","Nation"))
    {
        <h4>Nation Name :</h4>
        @Html.TextBoxFor(nation => nation.NationName)

        <h4>Nation's Government Type :</h4>
        @Html.TextBoxFor(nation => nation.GovernmentType)
    
        <h4>Nation's Economy Type :</h4>
        @Html.TextBoxFor(nation => nation.EconomyType)

        <h4>Nation's Geography Type :</h4>
        @Html.TextBoxFor(nation => nation.GeographyType)

        <input type = "submit" value = "create" />
    }
</div>

CivilizationReplica/Views/Nation/Game.cshtml
@model CivilizationReplica.Models.Nation
<head>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
     <script type="text/javascript">
        
        $(document).ready(function () {
            $('.events').click(function (event) {
                event.preventDefault();
                $.ajax({
                    url: '@Url.Action("EventGenerator")',
                    type: 'GET',
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function (result) {
                        var stringResult = '<h3>' + result + '</h3>';
                        }
                        $('#event').html(stringResult);
                    }
            });
        });
    </script>
</head>

@if(Model != null)
{
<div class="well">
	
    <p>@Html.DisplayNameFor(m=>m.NationName) : @Html.DisplayFor(m=>m.NationName)</p>
    <hr/>
    <p>@Html.DisplayNameFor(m=>m.GovernmentType) : @Html.DisplayFor(m=>m.GovernmentType)</p>
    <hr/>
    <p>@Html.DisplayNameFor(m=>m.EconomyType) : @Html.DisplayFor(m=>m.EconomyType)</p>
     <hr/>
    <p>@Html.DisplayNameFor(m=>m.GeographyType) : @Html.DisplayFor(m=>m.GeographyType)</p>
     <hr/>
    <p>@Html.DisplayNameFor(m=>m.Capital) : @Html.DisplayFor(m=>m.Capital)</p>
     <hr/>
    <p>@Html.DisplayNameFor(m=>m.Resources) : @Html.DisplayFor(m=>m.Resources)</p>
     <hr/>
    <p>@Html.DisplayNameFor(m=>m.Population) : @Html.DisplayFor(m=>m.Population)</p>
     <hr/>
    <p>@Html.DisplayNameFor(m=>m.Stability) : @Html.DisplayFor(m=>m.Stability)</p>

</div>
}
else
{
    @Html.ActionLink("Create Nation", "Create", "Nation")
}

<div id="event"></div>

<button class="btn btn-lg events">Events</button>

CivilizationReplica/Views/Nation/Index.cshtml
@model CivilizationReplica.Models.Nation

<head>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
     <script type="text/javascript">
		
        $(document).ready(function () {
            $('.play').click(function () {
                 $.ajax({
                    type: 'GET',
                    dataType: 'html',
                    url: '@Url.Action("Game")',
                    success: function (result) {
                        $('#nationInfo').html(result);
                     }
                    });
              });
		});
	</script>
</head>
<body>
	<button class="btn btn-lg play" type="button">Play</button>
	<div id="nationInfo"></div>
</body>